baseURL = "https://pla.bike/"
languageCode = "en-us"
title = "PLA Cycling Log"
theme = "gohugo-theme-ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "PLA's cycling log."
  twitter = "https://twitter.com/PLA1"
  youtube = "https://www.youtube.com/channel/UC5pKVW_GoO_5lHfxPIsCfFA"
  github = "https://github.com/pla1"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
