baseURL = "https://pla.bike/"
languageCode = "en-us"
title = "PLA Cycling Log"
theme = "gohugo-theme-ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10

[markup.goldmark.renderer]
  unsafe= true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "bike.png"
  description = "PLA's cycling log."
  twitter = "https://twitter.com/PLA1"
  youtube = "https://www.youtube.com/channel/UC5pKVW_GoO_5lHfxPIsCfFA"
  github = "https://github.com/pla1"
  rss = "https://pla.bike/index.xml"
  background_color_class = "bg-black"
  featured_image = "https://lh3.googleusercontent.com/jmag-Fg8sGWH7H876kOriI4my2GmkGYYyujXi90m4GcqoVNHWzHilx-HJ64haZ9EjeTgG9wVeEHaaUyHyDefookBsoRu4gkcNB2dekHIGD7hGO69y2HK7ZTRuVltW1FRzoJD8qnuN3o=w2400"
  recent_posts_number = 5
  env = "production"
